# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build
          command: mvn -B -q -DskipTests clean package
      - run:
          name: Test
          command: mvn -B -q test

workflows:
  regular:
    jobs:
      - build-and-test
